# Site settings
title: Neeldeep
description: >
  Tech Logs and Personal Experiences.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "neeldeep.github.io" # the base hostname & protocol for your site

author:
  fullname: Neeldeep Roy
  github: neeldeep
  twitter: neeldeeproy
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
markdown: kramdown
